top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/modules/mappers
builddir     = /home/scc/cfs/benchmark/httpd/modules/mappers
VPATH        = /home/scc/cfs/benchmark/httpd/modules/mappers

include $(top_srcdir)/build/special.mk

