top_srcdir   = /home/scc/httpd-2.2.22
top_builddir = /home/scc/httpd-2.2.22
srcdir       = /home/scc/httpd-2.2.22/modules/metadata
builddir     = /home/scc/httpd-2.2.22/modules/metadata
VPATH        = /home/scc/httpd-2.2.22/modules/metadata

include $(top_srcdir)/build/special.mk

