top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/modules/metadata
builddir     = /home/scc/cfs/benchmark/httpd/modules/metadata
VPATH        = /home/scc/cfs/benchmark/httpd/modules/metadata

include $(top_srcdir)/build/special.mk

