top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/modules/loggers
builddir     = /home/scc/cfs/benchmark/httpd/modules/loggers
VPATH        = /home/scc/cfs/benchmark/httpd/modules/loggers

include $(top_srcdir)/build/special.mk

