top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/modules/generators
builddir     = /home/scc/cfs/benchmark/httpd/modules/generators
VPATH        = /home/scc/cfs/benchmark/httpd/modules/generators

include $(top_srcdir)/build/special.mk

