top_srcdir   = /home/scc/httpd-2.2.22
top_builddir = /home/scc/httpd-2.2.22
srcdir       = /home/scc/httpd-2.2.22/modules/generators
builddir     = /home/scc/httpd-2.2.22/modules/generators
VPATH        = /home/scc/httpd-2.2.22/modules/generators

include $(top_srcdir)/build/special.mk

