top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/server/mpm/prefork
builddir     = /home/scc/cfs/benchmark/httpd/server/mpm/prefork
VPATH        = /home/scc/cfs/benchmark/httpd/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
