top_srcdir   = /home/scc/httpd-2.2.22
top_builddir = /home/scc/httpd-2.2.22
srcdir       = /home/scc/httpd-2.2.22/modules/echo
builddir     = /home/scc/httpd-2.2.22/modules/echo
VPATH        = /home/scc/httpd-2.2.22/modules/echo

include $(top_srcdir)/build/special.mk

