top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/modules/echo
builddir     = /home/scc/cfs/benchmark/httpd/modules/echo
VPATH        = /home/scc/cfs/benchmark/httpd/modules/echo

include $(top_srcdir)/build/special.mk

