top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/modules/filters
builddir     = /home/scc/cfs/benchmark/httpd/modules/filters
VPATH        = /home/scc/cfs/benchmark/httpd/modules/filters

include $(top_srcdir)/build/special.mk

