top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/modules/aaa
builddir     = /home/scc/cfs/benchmark/httpd/modules/aaa
VPATH        = /home/scc/cfs/benchmark/httpd/modules/aaa

include $(top_srcdir)/build/special.mk

