top_srcdir   = /home/scc/httpd-2.2.22
top_builddir = /home/scc/httpd-2.2.22
srcdir       = /home/scc/httpd-2.2.22/modules/cache
builddir     = /home/scc/httpd-2.2.22/modules/cache
VPATH        = /home/scc/httpd-2.2.22/modules/cache

include $(top_srcdir)/build/special.mk

