top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/modules/cache
builddir     = /home/scc/cfs/benchmark/httpd/modules/cache
VPATH        = /home/scc/cfs/benchmark/httpd/modules/cache

include $(top_srcdir)/build/special.mk

