top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/os
builddir     = /home/scc/cfs/benchmark/httpd/os
VPATH        = /home/scc/cfs/benchmark/httpd/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
