top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/modules/dav/lock
builddir     = /home/scc/cfs/benchmark/httpd/modules/dav/lock
VPATH        = /home/scc/cfs/benchmark/httpd/modules/dav/lock
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
