top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/modules/http
builddir     = /home/scc/cfs/benchmark/httpd/modules/http
VPATH        = /home/scc/cfs/benchmark/httpd/modules/http

include $(top_srcdir)/build/special.mk

