top_srcdir   = /home/scc/cfs/benchmark/httpd
top_builddir = /home/scc/cfs/benchmark/httpd
srcdir       = /home/scc/cfs/benchmark/httpd/server/mpm
builddir     = /home/scc/cfs/benchmark/httpd/server/mpm
VPATH        = /home/scc/cfs/benchmark/httpd/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
